### ISSUE TITLE
大分子量复合物建模

### ISSUE THREAD

**Issue by wh277** [biomed-AI/EModelX#1]
您好，目前软件对大分子量复合物的建模是不是对显存要求比较高，我处理一个48聚体，大约2 MDa，运行失败，显卡是3090 24G，能不能调用多显卡运行？

**Comment by ChenShengsGitHub** [comment]
可以根据log确定问题，据我所知显存不是瓶颈，往往是内存问题，可以通过缩小map大小（如将周围空白区域剪裁）到600*600*600左右。另外，多聚体也可能影响内存，尽量不要处理序列太长的多聚体，据我所知，200g内存处理600长度左右的40聚体是没什么问题的。最后，如果内存太小，可以尝试我们的服务器：https://bio-web1.nscc-gz.cn/app/EModelX

**Comment by wh277** [comment]
好的，谢谢
